name: HMCWraps
version: 1.3.2
main: de.skyslycer.hmcwraps.HMCWrapsPlugin
description: The best choice to make your items prettier.
author: Skyslycer
permissions:
  hmcwraps.admin:
    description: Gives access to all commands.
    default: op
  hmcwraps.commands.convert:
    description: Gives access to the convert command.
    children:
      hmcwraps.admin: true
  hmcwraps.commands.give.unwrapper:
    description: Gives access to giving physical unwrappers to players.
    children:
      hmcwraps.management: true
      hmcwraps.admin: true
      hmcwraps.commands.physical: true
  hmcwraps.commands.give.wrapper:
    description: Gives access to giving physical wrappers to players.
    children:
      hmcwraps.management: true
      hmcwraps.admin: true
      hmcwraps.commands.physical: true
  hmcwraps.commands.list:
    description: Gives access to the list command.
    children:
      hmcwraps.management: true
      hmcwraps.admin: true
  hmcwraps.commands.physical:
    description: Gives access to all commands related to physical wraps.
  hmcwraps.commands.preview:
    description: Gives access to starting a preview on behalf of others.
    children:
      hmcwraps.management: true
      hmcwraps.admin: true
  hmcwraps.commands.reload:
    description: Gives access to the reload command.
    children:
      hmcwraps.admin: true
  hmcwraps.commands.unwrap:
    description: Gives access to unwrap an item using commands (virtual).
    children:
      hmcwraps.management: true
      hmcwraps.admin: true
      hmcwraps.commands.virtual: true
  hmcwraps.commands.virtual:
    description: Gives access to all commands related to virtual wraps.
  hmcwraps.commands.wrap:
    description: Gives access to wrap an item using commands (virtual).
    children:
      hmcwraps.management: true
      hmcwraps.admin: true
      hmcwraps.commands.virtual: true
  hmcwraps.debug:
    description: Gives access to debug commands.
    children:
      hmcwraps.admin: true
  hmcwraps.management:
    description: Gives access to every command except the reload and the convert command.
  hmcwraps.wraps:
    description: Gives access to the wraps inventory (has to be enabled in config).
    children:
      hmcwraps.management: true
      hmcwraps.admin: true
api-version: 1.17
softdepend:
 - PlaceholderAPI
 - ItemsAdder
 - Oraxen
 - MythicMobs
