name: Build and deploy documentation to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 16
      - uses: gradle/gradle-build-action@v2
      - name: Build HTML
        run: ./gradlew api:dokkaHtml --no-daemon --stacktrace
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: api/build/dokka/html