name: Publish to Nexus

on:
  push:
    branches:
      - master

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest
    env:
      HAS_TOKEN: ${{ secrets.NEXUS_PASSWORD != '' }}
    if: ${{ env.HAVE_SONAR_TOKEN == 'true' }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 16
      - name: Build with Gradle
        run: ./gradlew api:clean api:build
      - name: Publish to Nexus
        run: ./gradlew api:publishMavenPublicationToSkyNexusRepository
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}