name: Publish to Skyslycer Repository

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'dependabot')"
    environment: build
    runs-on: ubuntu-latest
    env:
      HAS_TOKEN: ${{ secrets.NEXUS_PASSWORD != '' }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew api:clean api:build --no-daemon --stacktrace
      - name: Publish to Nexus
        if: ${{ env.HAS_TOKEN == 'true' }}
        run: ./gradlew api:publishMavenPublicationToSkyNexusRepository
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}